name: client_driver
description: A starting point for Dart libraries or applications.
version: 1.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  dio: ^5.2.1+1
  http: ^1.1.0
  logger: ^1.4.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3

